### ISSUE TITLE
Can't uninstall the plugin

### ISSUE THREAD

**Issue by cotufaloschiflones** [Icenium/cordova-plugin-webserver#6]
The problem came when I tried to uninstall the plugin, if I run "cordova plugin rm cordova-plugin-webserver" I'm getting the error:

```
Uninstalling cordova-plugin-webserver from ios 
Error: Uh oh!
Path must be a string. Received undefined
```

Any idea?

**Comment by ghost** [comment]
I removed it by first removing platforms then manually deleting the cordova-plugin-webserver folder in the plugins folder of my project
