### ISSUE TITLE
Merge projects

### ISSUE THREAD

**Issue by boedy** [Icenium/cordova-plugin-webserver#7]
Dear maintainers,

Currently there are two Cordova webserver plugins that use the same namespace. I just started maintaining this repo https://github.com/bykof/cordova-plugin-webserver. I was planning on publishing it to NPM as it's currently not on there, but noticed it was already associated with your plugin.

I would like to learn more about your project to see if there is some collaboration possible. What is this plugin mainly used for? I see that there is no javascript interface to interact with the native interface.

Would like to request you have a look at https://github.com/bykof/cordova-plugin-webserver to see if it fits your requirements.

If there are no further plans of maintaining this NPM module, I would like to request transfer of ownership on NPM.

**Comment by stoskov** [comment]
Hi,

Thank for reaching out. 

This is an old Cordova plugin that we do not maintain anymore. It has not been updated for the last four years, and most probably, his code is not secure anymore. To reflect that we have deprecated the plugin and moved the ownership to NPM. So, if you have an interest in maintaining it, you can reach out to NPM and discuss with them how to proceed. 

Hope this helps.

**Comment by boedy** [comment]
Thanks for getting back to me @stoskov. We'll reach out to NPM to see what's possible.
